### PR TITLE
[fix] #3462: Add burn asset command to client_cli

### LINKED ISSUE #3462: [BUG] Functionality not implemented for iroha_client_cli - asset burn
### OS and Environment

any

### GIT commit hash

3a1a84ae

### Minimum working example / Steps to reproduce

not implemented functionality ./iroha_clien_cli asset burn, but on documentation we have this point
https://hyperledger.github.io/iroha-2-docs/guide/bash.html#_5-registering-and-minting-assets
the same, we have a report on telegram group "Hyperladger Iroha Community" about this issue

```
Harini Ravikumar, [May 8, 2023 at 11:15:33]:
Hi 
In Iroha cli when doing burn the tokens I am facing the below issue.

error: Found argument 'burn' which wasn't expected, or isn't valid in this context

USAGE:
    iroha_client_cli asset <SUBCOMMAND>

For more information try --help

./iroha_client_cli asset burn \
    --account="mad_hatter@looking_glass" \
    --asset="tea#looking_glass" \
    --quantity="10"

This is the command I used.
```

### Actual result

its work fine

### Expected result

its not implemented

```
./iroha_client_cli assets burn \
    --account="mad_hatter@looking_glass" \
    --asset="tea#looking_glass" \
    --quantity="10"
error: The subcommand 'assets' wasn't recognized

	Did you mean 'asset'?

If you believe you received this message in error, try re-running with 'iroha_client_cli -- assets'

USAGE:
    iroha_client_cli [OPTIONS] <SUBCOMMAND>

For more information try --help

./iroha_client_cli asset --help                                                                               
iroha_client_cli-asset 
The subcommand related to assets

USAGE:
    iroha_client_cli asset <SUBCOMMAND>

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    get         Get info of asset
    help        Print this message or the help of the given subcommand(s)
    list        List assets
    mint        Command for minting asset in existing Iroha account
    register    Register subcommand of asset
    transfer    Transfer asset between accounts

```

### Logs in JSON format

nothing todo

### Who can help to reproduce?

@timofeevmd

### Notes

_No response_

### PR DESCRIPTION
**Pull request by mversic**
### Linked issue

Closes #3462

### Checklist

- [ ] I've read `CONTRIBUTING.md`
- [ ] I've used the standard signed-off commit format (or will squash just before merging)
- [ ] All applicable CI checks pass (or I promised to make them pass later)
- [ ] (optional) I've written unit tests for the code changes
- [ ] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

File: scripts/test_env.sh [hunk 1]
```diff
@@ -181,7 +179,11 @@ case $1 in
         run_n_peers "$N_PEERS"
         ;;
     cleanup)
-        clean_up_peers
+        # NOTE: It's not desireable for cleanup script to exit on the first failed command
```
Comment (appetrosyan) [inline scripts/test_env.sh:182]:
```suggestion
        # NOTE: It's not desirable for cleanup script to exit on the first failed command
```

**Review by appetrosyan — DISMISSED** [review]

**Review by appetrosyan — APPROVED** [review]

**Review by ilchu — APPROVED** [review]
