### PR TITLE
fix(core): Add checks for role presence before granting it

### LINKED ISSUE #5246: Granting unexisting role
It's possible to grant non existing role in genesis

### PR DESCRIPTION
**Pull request by aoyako**
Resolves #5246.

Verify that the role is present in the world before assigning it. 

Example that should pass:
```
{
    "Register": {
        "Role": {
            "id": "good_role",
            "permissions": [
                {
                    "name": "CanSetParameters",
                    "payload": null
                }
            ],
            "grant_to": "ed0120E9F632D3034BAB6BB26D92AC8FD93EF878D9C5E69E01B61B4C47101884EE2F99@garden_of_live_flowers"
        }
    }
},
{
    "Grant": {
        "Role": {
            "object": "good_role",
            "destination": "ed0120CE7FA46C9DCE7EA4B125E2E36BDB63EA33073E7590AC92816AE1E861B7048B03@wonderland"
        }
    }
}
```

Example that should fail:
```
{
    "Grant": {
        "Role": {
            "object": "bad_role",
            "destination": "ed0120CE7FA46C9DCE7EA4B125E2E36BDB63EA33073E7590AC92816AE1E861B7048B03@wonderland"
        }
    }
}
```

### CODE REVIEW

**Review by s8sato — DISMISSED** [review]

**Review by s8sato — DISMISSED** [review]

**Review by s8sato — DISMISSED** [review]

File: crates/iroha/tests/roles.rs [hunk 1]
```diff
@@ -263,3 +263,16 @@ fn grant_revoke_role_permissions() -> Result<()> {
...
+#[should_panic(expected = "a peer exited unexpectedly")]
+fn grant_unexisting_role_in_genesis_fail() {
+    // Grant Alice UNEXISTING role
+    let alice_id = ALICE_ID.clone();
+    let role_id = "UNEXISTING".parse::<RoleId>().unwrap();
+    let grant_genesis_role = Grant::account_role(role_id, alice_id);
+
+    let _result = NetworkBuilder::new()
+        .with_genesis_instruction(grant_genesis_role)
+        .start_blocking();
```
Comment (0x009922) [inline crates/iroha/tests/roles.rs:277]: It'd be great to extend the `NetworkBuilder` in a way that it intercepts the error printed by Iroha, so that we can put a more precise assertion here.

**Review by 0x009922 — APPROVED** [review]

**Review by s8sato — APPROVED** [review]

File: crates/iroha/tests/roles.rs (hunk 1 above)
Comment (aoyako) [reply crates/iroha/tests/roles.rs:277]: #5324
