### PR TITLE
[fix] #1990: Enable peer startup via env vars in the absence of `config.json`

### LINKED ISSUE #1990: Support running Iroha without `config.json` using pure environment variables.

### PR DESCRIPTION
**Pull request by ilchu**
Signed-off-by: Ilia Churin <ilia.ch@netogami.net>

### Description of the Change

In the case when the minimal cli client (`iroha`) was provided with no `config.json` either in the same directory or as an environment variable, do not stop the execution, but instead require that all the variables from the default json be provided as environment variables too, and load them onto default configuration.

### Issue

Resolves #1990.

### Benefits
Presumably easier and more flexible setup of peer through cli.

### Possible Drawbacks
As the fix chooses to fall back on default impl for config, it has the same problems that were discussed in #2101 and  #2118. The question is which variables should be allowed to be set via environment, and which subset of them should be required when using default, if we're going to stick with it at all. As of now, the default configuration is generated with `Default` and all the variables from the `configs/peer/config.json` are required to proceed if no file was found.

### CODE REVIEW

File: cli/src/lib.rs [hunk 1]
```diff
@@ -143,7 +146,9 @@ where
         broker: Broker,
     ) -> Result<Self> {
         if !config.disable_panic_terminal_colors {
-            color_eyre::install()?;
+            if let Err(e) = color_eyre::install() {
+                iroha_logger::error!("Tried to install eyre_hook twice: {:?}", e);
```
Comment (mversic) [inline cli/src/lib.rs:150]: why does this happen?

File: cli/src/main.rs [hunk 2]
```diff
@@ -27,6 +27,28 @@ async fn main() -> Result<(), color_eyre::Report> {
 
     if let Ok(config_path) = std::env::var("IROHA2_CONFIG_PATH") {
         args.config_path = std::path::PathBuf::from_str(&config_path)?;
+    } else {
+        if !Path::new("config.json").exists() {
```
Comment (mversic) [inline cli/src/main.rs:31]:
```suggestion
    } 
    if !args.config_path.exists() {
```

File: cli/src/main.rs [hunk 3]
```diff
@@ -58,4 +80,17 @@ fn print_help() {
     println!("    IROHA2_CONFIG_PATH is the location of your `config.json`");
     println!("    IROHA2_GENESIS_PATH is the location of `genesis.json`");
     println!("If either of these is not provided, Iroha checks the current directory.");
+    println!(
+        "Additionally, in case of absense of both IROHA2_CONFIG_PATH and `config.json`
```
Comment (mversic) [inline cli/src/main.rs:84]:
```suggestion
        "Additionally, in case of absence of both IROHA2_CONFIG_PATH and `config.json`
```

File: cli/README.md [hunk 4]
```diff
@@ -77,7 +77,7 @@ cargo run --bin kagami -- crypto --json
 
 For the Iroha peer binary to run, a configuration file must be provided. Iroha will not run with defaults if the configuration file is not available.
 
-The Iroha binary looks for either a file `config.json` in the current directory, or for a JSON file `IROHA2_CONFIG_PATH`. If the latter environment variable is defined, but not a valid configuration file, the Iroha peer binary will exit and do nothing.
+The Iroha binary looks for either a file `config.json` in the current directory, or for a JSON file `IROHA2_CONFIG_PATH`. If the latter environment variable is defined, but not a valid configuration file, the Iroha peer binary will exit and do nothing. If neither of those is provided, all the fields from default `config.json` should be specified as environment variables.
```
Comment (mversic) [inline cli/README.md:80]: As I see from the implementation it seems that env variable `IROHA2_CONFIG_PATH` takes precedence over `config.json` in current directory

Comment (mversic) [reply cli/README.md:80]:
```suggestion
The Iroha binary looks for either a file `config.json` in the current directory, or for a JSON file `IROHA2_CONFIG_PATH`. If the configuration file is not valid, the Iroha peer binary will exit and do nothing. If neither of those is provided, all the fields from default `config.json` should be specified as environment variables.
```

File: cli/src/main.rs (hunk 2 above)
Comment (mversic) [reply cli/src/main.rs:31]: this would mean that env variables will be read from if `IROHA2_CONFIG_PATH` doesn't exist or `config.json` doesn't exist

**Review by mversic — CHANGES_REQUESTED** [review]

File: cli/src/lib.rs (hunk 1 above)
Comment (ilchu) [reply cli/src/lib.rs:150]: Was not able to trace the exact reason, but somehow with this workflow when no config was provided color_eyre kept crashing. AFAICT the only other spots where `install()` is used are `kagami` and `logger`, but they don't seem to be called at that stage. Will double check the error again, but this was a stumbling point for me.

Comment (mversic) [reply cli/src/lib.rs:150]: I'm asking because I think this also happened to sdk devs when bootstraping iroha

Comment (ilchu) [reply cli/src/lib.rs:150]: Then at least it's not only me, but something in the code. I guess then as a workaround this will suffice for now, and I'll create a separate issue for this later today.

Comment (appetrosyan) [reply cli/src/lib.rs:150]: Kagami is a completely unrelated executable, so this is probably the only place this happens. Log and ignore for now, but we ned to figure out why this happens. IMO there's a tokio task that tries to do the same thing in a different thread and breaks the install process.

File: cli/README.md [hunk 5]
```diff
@@ -77,7 +77,7 @@ cargo run --bin kagami -- crypto --json
 
 For the Iroha peer binary to run, a configuration file must be provided. Iroha will not run with defaults if the configuration file is not available.
 
-The Iroha binary looks for either a file `config.json` in the current directory, or for a JSON file `IROHA2_CONFIG_PATH`. If the latter environment variable is defined, but not a valid configuration file, the Iroha peer binary will exit and do nothing.
+The Iroha binary looks for either a file `config.json` in the current directory, or for a JSON file `IROHA2_CONFIG_PATH`. If the configuration file is not valid, the Iroha peer binary will exit and do nothing. If neither of those is provided, all the fields from default `config.json` should be specified as environment variables.
```
Comment (Arjentix) [inline cli/README.md:80]: I'd add the information, that if a config was found and some env variables are defined, then they will override the corresponding fields

**Review by mversic — DISMISSED** [review]

File: cli/src/main.rs [hunk 6]
```diff
@@ -58,4 +77,17 @@ fn print_help() {
...
+as follows:"
+    );
+    println!("    IROHA_TORII is the torii gateway config");
+    println!("    IROHA_SUMERAGI is the consensus config");
+    println!("    IROHA_KURA is block storage config");
+    println!("    IROHA_BLOCK_SYNC is block synchronization config");
+    println!("    IROHA_PUBLIC_KEY is the peer's public key");
+    println!("    IROHA_PRIVATE_KEY is the peers' private key");
+    println!("    IROHA_GENESIS is the genesis block config");
+    println!("Examples of these variables can be seen in the default `configs/peer/config.json`.")
```
Comment (outoftardis) [inline cli/src/main.rs:92]:
```suggestion
    println!("Examples of these variables can be found in the default `configs/peer/config.json`.")
```

File: cli/src/main.rs [hunk 7]
```diff
@@ -2,6 +2,7 @@
 
 use std::str::FromStr;
 
+use eyre::WrapErr;
```
Comment (appetrosyan) [inline cli/src/main.rs:5]:
```suggestion
use eyre::WrapErr as _;
```

File: cli/src/main.rs [hunk 8]
```diff
@@ -58,4 +77,17 @@ fn print_help() {
     println!("    IROHA2_CONFIG_PATH is the location of your `config.json`");
     println!("    IROHA2_GENESIS_PATH is the location of `genesis.json`");
     println!("If either of these is not provided, Iroha checks the current directory.");
+    println!(
+        "Additionally, in case of absence of both IROHA2_CONFIG_PATH and `config.json`
+in the current directory, all the variables from `config.json` should be set via the environment
+as follows:"
+    );
```
Comment (appetrosyan) [inline cli/src/main.rs:84]: Explain that they need to passed as a JSON string. I'd add an example of that could be run from the command line in the comments/docs.

File: cli/README.md [hunk 9]
```diff
@@ -77,7 +77,13 @@ cargo run --bin kagami -- crypto --json
...
...94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b\"},{\"address\": \"127.0.0.1:1338\",\"public_key\": \"ed0120cc25624d62896d3a0bfd8940f928dc2abf27cc57cefeb442aa96d9081aae58a1\"},{\"address\": \"127.0.0.1:1339\",\"public_key\": \"ed0120faca9e8aa83225cb4d16d67f27dd4f93fc30ffa11adc1f5c88fd5495ecc91020\"},{\"address\": \"127.0.0.1:1340\",\"public_key\": \"ed01208e351a70b6a603ed285d666b8d689b680865913ba03ce29fb7d13a166c4e7f1f\"}]}" IROHA_KURA="{\"INIT_MODE\": \"strict\",\"BLOCK_STORE_PATH\": \"./blocks\"}" IROHA_BLOCK_SYNC="{\"GOSSIP_PERIOD_MS\": 10000,\"BATCH_SIZE\": 2}" IROHA_PUBLIC_KEY="ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b" IROHA_PRIVATE_KEY="{\"digest_function\": \"ed25519\",\"payload\": \"282ed9f3cf92811c3818dbc4ae594ed59dc1a2f78e4241e31924e101d6b1fb831c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b\"}" IROHA_GENESIS="{\"ACCOUNT_PUBLIC_KEY\": \"ed01204cffd0ee429b1bdd36b3910ec570852b8bb63f18750341772fb46bc856c5caaf\",\"ACCOUNT_PRIVATE_KEY\": {\"digest_function\": \"ed25519\",\"payload\": \"d748e18ce60cb30dea3e73c9019b7af45a8d465e3d71bcc9a5ef99a008205e534cffd0ee429b1bdd36b3910ec570852b8bb63f18750341772fb46bc856c5caaf\"}}" ./iroha
```
Comment (appetrosyan) [inline cli/README.md:85]: This is a little ugly, but this is meant to be technical documentation. Add some `<details>` tags around it and we can merge.

**Review by appetrosyan — APPROVED** [review]

**Review by mversic — APPROVED** [review]
