### PR TITLE
[fix] #3627: Transaction atomicity through cloning

### LINKED ISSUE #3627: Insure transaction atomicity
As part of implementing runtime validator RFC (#3615) we need to make sure that if isi returns error no changes was made to wsv.

Some guardrails could be added to ensure that `hash(wsv_before) == hash(wsv_after_error)`.

### PR DESCRIPTION
**Pull request by Erigara**
## Description

Apply transaction on cloned wsv and replace original one in case of successful execution. 

### Linked issue

Partially closes #3627 

### Benefits

Transaction execution within block is atomic.

### Drawbacks

Cloning `wsv` will be costly in case of large wsv.

However on the current benchmarks i don't see significant differences.

We should explore time/space tradeoffs for improved solution.
Consider implementation of transaction rollbacks.

### Checklist

- [x] I've read `CONTRIBUTING.md`
- [x] I've used the standard signed-off commit format (or will squash just before merging)
- [x] All applicable CI checks pass (or I promised to make them pass later)
- [x] (optional) I've written unit tests for the code changes
- [x] I replied to all comments after code review, marking all implemented changes with thumbs up

### CODE REVIEW

File: core/src/block.rs [hunk 1]
```diff
@@ -792,4 +792,58 @@ mod tests {
 
         Revalidate::revalidate::<true>(&valid_block, wsv).unwrap();
     }
+
+    #[test]
+    fn transactions_are_atomic() {
```
Comment (appetrosyan) [inline core/src/block.rs:797]: This isn't exactly whqt the test is testing. Atomicity can be established only using formal verification or at the very least a proptest.

File: core/src/block.rs [hunk 2]
```diff
@@ -792,4 +792,58 @@ mod tests {
...
+        // Predefined world state
+        let alice_id = AccountId::from_str("alice@wonderland").expect("Valid");
+        let alice_keys = KeyPair::generate().expect("Valid");
+        let account =
+            Account::new(alice_id.clone(), [alice_keys.public_key().clone()]).build(&alice_id);
+        let domain_id = DomainId::from_str("wonderland").expect("Valid");
+        let mut domain = Domain::new(domain_id).build(&alice_id);
+        assert!(domain.add_account(account).is_none());
```
Comment (appetrosyan) [inline core/src/block.rs:805]: Needs explanation.

File: core/src/block.rs (hunk 1 above)
Comment (appetrosyan) [reply core/src/block.rs:797]: `failbox_atomic_revert` maybe? There's also a successful transaction, which imposes the ordering.

**Review by appetrosyan — APPROVED** [review]

File: core/src/block.rs (hunk 2 above)
Comment (Erigara) [reply core/src/block.rs:805]: What exactly? it's standard think we use to create domain and accounts for wsv.

File: core/src/block.rs (hunk 1 above)
Comment (Erigara) [reply core/src/block.rs:797]: `failed_transaction_revert` maybe?

Comment (appetrosyan) [reply core/src/block.rs:797]: `failed_transactions_revert`.

File: client/tests/integration/connected_peers.rs [hunk 3]
```diff
@@ -54,20 +54,19 @@ fn connected_peers_with_f(faults: u64) -> Result<()> {
...
-    client.submit(unregister_peer)?;
-    thread::sleep(pipeline_time * 2);
+    client.submit_blocking(unregister_peer)?;
+    thread::sleep(pipeline_time * 2); // Wait for some time to allow peers to connect
     status = client.get_status()?;
     assert_eq!(status.peers, n_peers - 2);
     assert_eq!(status.blocks, 3);
     status = peer_client.get_status()?;
     assert_eq!(status.peers, 0);
-    assert_eq!(status.blocks, 3);
```
Comment (Erigara) [inline client/tests/integration/connected_peers.rs:64]: We can't grantee, that `ObservingPeer` will sync latest block until it will be disconnected from the network.

**Review by appetrosyan — APPROVED** [review]

File: core/src/block.rs [hunk 4]
```diff
@@ -792,4 +792,61 @@ mod tests {
...
+            event_recommendations: Vec::new(),
+            view_change_index: 0,
+            committed_with_topology: Topology::new(Vec::new()),
+            key_pair: alice_keys,
+            wsv,
+        }
+        .build();
+
+        // The first transaction should be rejected
+        assert!(valid_block.transactions[0].error.is_some());
```
Comment (appetrosyan) [inline core/src/block.rs:847]:
```suggestion
        assert!(valid_block.transactions[0].error.is_some(), "The first transaction should be rejected, as it contains `FailBox`.");
```

File: core/src/block.rs [hunk 5]
```diff
@@ -792,4 +792,61 @@ mod tests {
...
+
+        // The second transaction should be accepted
+        assert!(valid_block.transactions[1].error.is_none());
```
Comment (appetrosyan) [inline core/src/block.rs:850]:
```suggestion
        assert!(valid_block.transactions[1].error.is_none(), "The second transaction should be accepted.");
```

File: core/src/block.rs [hunk 6]
```diff
@@ -792,4 +792,61 @@ mod tests {
...
+        let domain_id = DomainId::from_str("domain").expect("Valid");
+        let create_domain = RegisterBox::new(Domain::new(domain_id));
+        let asset_definition_id = AssetDefinitionId::from_str("coin#domain").expect("Valid");
+        let create_asset = RegisterBox::new(AssetDefinition::quantity(asset_definition_id));
+        let instructions_1: [InstructionBox; 2] = [
+            create_domain.clone().into(),
+            FailBox::new("Always fail").into(),
+        ];
+        let instructions_2: [InstructionBox; 2] = [create_domain.into(), create_asset.into()];
+        let tx_1 = TransactionBuilder::new(alice_id.clone())
```
Comment (appetrosyan) [inline core/src/block.rs:823]:
```suggestion
        let tx_fail = TransactionBuilder::new(alice_id.clone())
```

File: core/src/block.rs [hunk 7]
```diff
@@ -792,4 +792,61 @@ mod tests {
...
+            .with_instructions(instructions_1)
+            .sign(alice_keys.clone())
+            .expect("Valid");
+        let tx_1 = AcceptedTransaction::accept(tx_1, transaction_limits).expect("Valid");
+        let tx_2 = TransactionBuilder::new(alice_id)
```
Comment (appetrosyan) [inline core/src/block.rs:828]:
```suggestion
        let tx_accept = TransactionBuilder::new(alice_id)
```

**Review by appetrosyan — APPROVED** [review]

**Review by SamHSmith — APPROVED** [review]
LGTM

File: core/src/sumeragi/mod.rs [hunk 8]
```diff
@@ -55,13 +55,13 @@ struct LastUpdateMetricsData {
...
 pub struct SumeragiHandle {
     public_wsv_receiver: watch::Receiver<WorldStateView>,
-    message_sender: mpsc::SyncSender<MessagePacket>,
     metrics: Metrics,
     last_update_metrics_mutex: Arc<Mutex<LastUpdateMetricsData>>,
     network: IrohaNetwork,
     kura: Arc<Kura>,
     queue: Arc<Queue>,
     _thread_handle: Arc<ThreadHandler>,
+    message_sender: mpsc::SyncSender<MessagePacket>,
```
Comment (QuentinI) [inline core/src/sumeragi/mod.rs:64]: Does this need to be dropped last for some reason?

File: core/benches/validate_blocks/validate_blocks.rs [hunk 9]
```diff
@@ -0,0 +1,242 @@
...
+    }
+
+    /// Run benchmark body.
+    ///
+    /// # Errors
+    /// - Not enough blocks
+    /// - Failed to apply block
+    ///
+    /// # Panics
+    /// If wsv doesn't one block ahead of finalized wsv.
```
Comment (QuentinI) [inline core/benches/validate_blocks/validate_blocks.rs:216]: Did you mean "isn't"?

**Review by QuentinI — APPROVED** [review]

File: core/benches/validate_blocks/validate_blocks.rs (hunk 9 above)
Comment (Erigara) [reply core/benches/validate_blocks/validate_blocks.rs]: Yes, fixed

**Review by appetrosyan — APPROVED** [review]

File: core/src/sumeragi/mod.rs (hunk 8 above)
Comment (appetrosyan) [reply core/src/sumeragi/mod.rs:64]: Relevant to #3584

**Review by SamHSmith — DISMISSED** [review]

File: core/src/sumeragi/mod.rs (hunk 8 above)
Comment (QuentinI) [reply core/src/sumeragi/mod.rs:64]: Can you please add a comment explaining it then?

**Review by QuentinI — APPROVED** [review]

**Review by SamHSmith — APPROVED** [review]
