### PR TITLE
fix: Expired transaction event appears after commit

### LINKED ISSUE #5389: `TransactionStatus::Expired` appears while the transaction is committed as approved
Reported by a testnet volunteer

### PR DESCRIPTION
**Pull request by aoyako**
Resolves #5389 by removing additional `expired` events. Original reports are kept in `get_transactions_for_block`.

### CODE REVIEW

File: crates/iroha/tests/triggers/time_trigger.rs [hunk 1]
```diff
@@ -131,7 +131,7 @@ fn pre_commit_trigger_should_be_executed() -> Result<()> {
         test_client.submit(sample_isi)?;
 
         // Waiting for empty block to be committed
-        std::thread::sleep(network.pipeline_time());
+        std::thread::sleep(2*network.pipeline_time());
```
Comment (aoyako) [inline crates/iroha/tests/triggers/time_trigger.rs:134]: Should there be any functionality to wait for an empty block?

Comment (0x009922) [reply crates/iroha/tests/triggers/time_trigger.rs]: In #5380 I refined block hooks in the test network and rewrote all such places into something like

```rs
// accounts for empty blocks too
network.ensure_blocks_with(|height| height.total == 2).await; 
```

File: crates/iroha_core/src/queue.rs [hunk 2]
```diff
@@ -172,10 +172,10 @@ impl Queue {
...
-        if self.is_expired(tx) {
-            Err(Error::Expired)
-        } else if tx.is_in_blockchain(state_view) {
+        if tx.is_in_blockchain(state_view) {
             Err(Error::InBlockchain)
+        } else if self.is_expired(tx) {
+            Err(Error::Expired)
         } else {
             Ok(())
         }
```
Comment (0x009922) [inline crates/iroha_core/src/queue.rs:181]: Would be good to add a simple unit test to ensure this behaviour.

**Review by 0x009922 — APPROVED** [review]
LGTM if CI passes.

**Review by s8sato — APPROVED** [review]

**Review by 0x009922 — APPROVED** [review]
